### ISSUE TITLE
[question] [aurelia-sortable] Multiple columns using type flags

### ISSUE THREAD

**Issue by petekc1** [oribella/oribella#34]
I'm currently using the demo example (http://oribella.github.io/aurelia-sortable/#/advanced)

It works as intended however, when additional columns are added it starts to get a little awkward to use.

This works perfectly fine,

Original

```
  public groups = [
    {
      name: 'Unordered Column', typeFlag: 3, items: Array.from(Array(11), (_, i) => i).map((i) => {
        return {
          name: i,
          typeFlag: i % 2 === 0 ? 2 : 1,
          lockedFlag: i === 0 ? 3 : 0
        };
      })
    },
    {
      name: 'Odds', typeFlag: 1, items: []
    },
    {
      name: 'Evens', typeFlag: 2, items: []
    },
  ];
```

![same](https://user-images.githubusercontent.com/32603341/39395373-077ff04e-4b32-11e8-8a42-c324a0ce2fe0.PNG)

-----------

Slightly modified.

Items with Type Flag 2 can move freely into Column 2 and 3, Items with Type Flag 3 can move freely between Column 1, 2, 3 and Items with Type Flag 4 can only move into Column 4.

Is there something I'm missing about how this all works?

```
  public groups = [
    {
      name: 'Unordered Column', typeFlag: 1, items: [
        {
          name: "Item 1",
          typeFlag: 2,
          lockedFlag: 0
        },
        {
          name: "Item 2",
          typeFlag: 2,
          lockedFlag: 0
        },
        {
          name: "Item 3",
          typeFlag: 3,
          lockedFlag: 0
        },
        {
          name: "Item 4",
          typeFlag: 3,
          lockedFlag: 0
        },
        {
          name: "Item 5",
          typeFlag: 4,
          lockedFlag: 0
        }
      ]
    },
    {
      name: 'Column 2', typeFlag: 2, items: []
    },
    {
      name: 'Column 3', typeFlag: 3, items: []
    },
    {
      name: 'Column 4', typeFlag: 4, items: []
    }
  ];
```

![modified](https://user-images.githubusercontent.com/32603341/39395383-371573ec-4b32-11e8-90d2-9a2bb2cf6014.PNG)

---

My end goal of this is to move items chronologically. (Col 1 into Col 2, Col 2 into Col 3 and so on) Or allow moving into specific columns. (Col 1 into Col 2 and 3 but not 4, once moved into col 2 or 3 allow movement into col 4).

**Comment by stoffeastrom** [comment]
HI @PTKC,

The `TypeFlag` is an abstract bit flag meaning it will allow moves if the same bits are set

0000
0001
0011
0111

So make sure to set them to what you want. If you want them exclusively.

Does that help you?

**Comment by stoffeastrom** [comment]
Update the [docs](https://oribella.github.io/oribella/docs/aurelia-sortable.html#typeflag)

**Comment by stoffeastrom** [comment]
So, this enables more advanced scenarios for example imagine that you have a list that is a bucket of different things and you want to allow drag n drop all other list items to that. However for the other lists you only want to allow in the list or to the bucket.

Hope it clarifies it for you :)

**Comment by PTKC** [comment]
@stoffeastrom Ah, Of course, that clarifies everything! Thanks for the help. :)
